// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Projekt")>]
[<assembly: AssemblyProductAttribute("Projekt")>]
[<assembly: AssemblyDescriptionAttribute("A command line tool for creating and updating F# project files")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
[<assembly: InternalsVisibleToAttribute("Projekt.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Projekt"
    let [<Literal>] AssemblyProduct = "Projekt"
    let [<Literal>] AssemblyDescription = "A command line tool for creating and updating F# project files"
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
    let [<Literal>] InternalsVisibleTo = "Projekt.Tests"
